# snap package name - need to be same in a path in TransactionDecorator sh entrypoint
name: transaction-decorator
base: core22
version: '1.0.0'
summary: TransactionDecorator is a utility to decorate transactions.
description: This application provides an interface for managing transactions.
grade: stable
confinement: classic

apps:
#  this needs to be the same name as top-level "name:" if not then to run snap from terminal:
#  <top-level-name>.<name-in-apps> example if this name in "apps: will be transaction-decorator-app:
#  to run in terminal you will need command: transaction-decorator.transaction-decorator-app
  transaction-decorator:
    environment:
      TRANSACTION_DECORATOR_SNAP_NAME: transaction-decorator
    command: usr/bin/transaction-decorator-entrypoint
    desktop: usr/share/applications/transaction_decorator.desktop
    plugs:
      - desktop
      - x11
      - wayland
      - unity7
      - home
      - network

  run-user-data-copy:
    command: user-data-copy.sh
    daemon: simple
    restart-condition: never

parts:
  assets-part:
    plugin: dump
    source: .
    organize:
      'src/': usr/lib/transaction-decorator/src/
      'icons/': usr/share/transaction-decorator/icons/
      'csv/allTransactions.csv': usr/share/transaction-decorator/csv/
      'dictionary/': usr/share/transaction-decorator/dictionary/
      'linux/snap/transaction_decorator.desktop': usr/share/applications/transaction_decorator.desktop
      'linux/snap/transaction-decorator-entrypoint': usr/bin/transaction-decorator-entrypoint

  python-part:
    after: [ assets-part ]
    plugin: nil
    source: .
    build-packages:
      - python3-dev  # Ensure Python development files are available
      - python3-setuptools  # Required for setup.py
      - python3-pip  # In case you need pip
    override-build: |
      # Use the Python from the build environment
      python3 $SNAPCRAFT_PART_SRC/setup.py install --root=$SNAPCRAFT_PART_INSTALL

  hooks-part:
    after: [ python-part ]
    plugin: dump
    source: linux/snap/hooks


#  transaction-decorator-part:
#    after: [ hooks-part ]
##    after: [ assets-part ]
#
#    plugin: python
#
#    #    directive tells Snapcraft to include the entire project directory as the context for the snap build
#    #    it is relative to terminal working directory (pwd) from which script was launched
#    source: .

