# snap package name - need to be same in a path in TransactionDecorator sh entrypoint
name: transaction-decorator
base: core22
version: '1.0.1'
summary: TransactionDecorator is a utility to decorate transactions.
description: This application provides an interface for managing transactions.
grade: stable
confinement: classic

apps:
#  this needs to be the same name as top-level "name:" if not then to run snap from terminal:
#  <top-level-name>.<name-in-apps> example if this name in "apps: will be transaction-decorator-app:
#  to run in terminal you will need command: transaction-decorator.transaction-decorator-app
  transaction-decorator:
    environment:
      TRANSACTION_DECORATOR_SNAP_NAME: transaction-decorator
    command: usr/bin/transaction-decorator-entrypoint
    desktop: usr/share/applications/transaction_decorator.desktop
    plugs:
      - desktop
      - x11
      - wayland
      - unity7
      - home
      - network

  run-user-data-copy:
    command: user-data/user-data-copy.sh
    daemon: simple
    restart-condition: never

parts:
  sources-part:
    plugin: dump
    source: src/
    organize:
      '*': usr/lib/transaction-decorator/src/

  icons-part:
    after: [ sources-part ]
    plugin: dump
    source: icons/
    organize:
      '*': usr/share/transaction-decorator/icons/

  csv-part:
    after: [ icons-part ]
    plugin: dump
    source: csv/
    organize:
      'allTransactions.csv': usr/share/transaction-decorator/csv/

  dictionary-part:
    after: [ csv-part ]
    plugin: dump
    source: dictionary/
    organize:
      '*': usr/share/transaction-decorator/dictionary/

  entrypoint-part:
    after: [ dictionary-part ]
    plugin: dump
    source: linux/snap/
    organize:
      'transaction_decorator.desktop': usr/share/applications/
      'transaction-decorator-entrypoint': usr/bin/

  python-part:
    after: [ entrypoint-part ]
    plugin: nil
    source: .
    build-packages:
      - python3-dev  # Ensure Python development files are available
      - python3-setuptools  # Required for setup.py
      - python3-pip
    override-build: |
      # Use the Python from the build environment
      python3 $SNAPCRAFT_PART_SRC/setup.py install --root=$SNAPCRAFT_PART_INSTALL
