# snap package name - need to be same in a path in TransactionDecorator sh entrypoint
name: transaction-decorator
base: core22
version: '1.0.0'
summary: TransactionDecorator is a utility to decorate transactions.
description: This application provides an interface for managing transactions.
grade: stable
confinement: strict

apps:
#  this needs to be the same name as top-level "name:" if not then to run snap from terminal:
#  <top-level-name>.<name-in-apps> example if this name in "apps: will be transaction-decorator-app:
#  to run in terminal you will need command: transaction-decorator.transaction-decorator-app
  transaction-decorator:
    environment:
      TRANSACTION_DECORATOR_SNAP_NAME: transaction-decorator
    command: usr/bin/transaction-decorator-entrypoint
    desktop: usr/share/applications/transaction_decorator.desktop
#    extensions:
#      - desktop-gtk3
#    extensions:
#      - gnome-3-38
    plugs:
      - desktop
      - x11
      - wayland
      - unity7
      - home
      - network

plugs:
  gtk-3-themes:
    interface: content
    target: $SNAP/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/sounds
    default-provider: gtk-common-themes

parts:
  assets-part:
    plugin: dump
    source: .
    organize:
      'src/': usr/lib/transaction-decorator/src/
      'icons/': usr/share/transaction-decorator/icons/
      'csv/allTransactions.csv': usr/share/transaction-decorator/csv/
      'dictionary/': usr/share/transaction-decorator/dictionary/
      'linux/snap/transaction_decorator.desktop': usr/share/applications/transaction_decorator.desktop
      'linux/snap/transaction-decorator-entrypoint': usr/bin/transaction-decorator-entrypoint

  hooks-part:
    plugin: dump
    source: linux/snap/hooks
    organize:
      'user-data-copy.sh': snap/hooks/install

  transaction-decorator-part:
    after: [ assets-part ]
    plugin: python
    build-environment:
      - PYTHONPATH: $SNAP/usr/lib/transaction-decorator/src

    #    directive tells Snapcraft to include the entire project directory as the context for the snap build
    #    it is relative to terminal working directory (pwd) from which script was launched
    source: .

#    recommended packages for python build phase
    build-packages:
      - python3-dev
      - build-essential

#    required to install python packages specified in setu.py file
    python-packages:
      - setuptools
      - wheel

    #    packages required by app to run on linux (will be put into snap files)
    stage-packages:
      - libxcb-xinerama0
      - libxcb1
      - libx11-xcb1
      - libglu1-mesa
      - libxrender1
      - libxi6
      - libxkbcommon-x11-0
      - libgl1-mesa-glx
      - libegl1
      - libx11-6
      - libxext6
      - libfontconfig1
      - libfreetype6
      - libpulse0
      - libwayland-cursor0
      - libwayland-egl1
      - libxcomposite1
      - libxdamage1
      - libxrandr2
      - libxtst6
      - libasound2
      - libnspr4
      - libnss3
      - libxkbfile1
      - libcups2
      - libxcb-cursor0
      - libxcb-icccm4
      - libxcb-image0
      - libxcb-keysyms1
      - libxcb-render-util0
      - libxcb-render0
      - libxcb-shape0
      - libxcb-xkb1
      - libxkbcommon0
      - libwayland-client0
      - libwayland-server0
      - libwayland-egl-backend-dev
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-ugly
      - libgstreamer-gl1.0-0
      - libgstreamer1.0-0
      - libgstreamer1.0-dev
      - libatk1.0-0
      - libcairo-gobject2
      - libcairo2
      - libgdk-pixbuf2.0-0
      - libgtk-3-0
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libspeechd2
      - odbcinst
      - odbcinst1debian2
      - unixodbc
      - libsqlite3-0
      - hicolor-icon-theme
      - gnome-icon-theme
      - adwaita-icon-theme-full

