APP_NAME = 'TransactionDecorator'

# Processing constants
CSV_DELIMITER = ';'
LABELS_DELIMITER = ','
NOTE_COLUMN = 'Note'
LABELS_COLUMN = 'Labels'

# Internal constants paths
APP_ICON = 'icons/logo.png'

MAXIMIZE_ICON_PATH = 'icons/maximize.png'
RESTORE_ICON_PATH = 'icons/restore.png'
MINIMIZE_ICON_PATH = 'icons/minimize.png'
CLOSE_ICON_PATH = 'icons/close.png'

DICTIONARY_ICON_PATH = 'icons/dictionary.png'
FILE_BACKUP_ICON_PATH = 'icons/file-backup.png'
CSV_FILE_ICON_PATH = 'icons/csv-file.png'

# External / User constants paths
DICTIONARY_DIRECTORY_PATH = './dictionary'
FILE_BACKUP_DIRECTORY_PATH = './backup'
CSV_FILE_DIRECTORY_PATH = './csv'

DICTIONARY_NAME = 'labels-dictionary.json'
TRANSACTION_CSV_NAME = 'allTransactions.csv'

# UI setup
CONFIRMATION_BUTTON_TEXT = 'OK'

# UI size
CONTROL_BUTTON_ICON_SIZE = '15px'
FOLDER_ICON_SIZE = '30px'
BORDER_RADIUS = '10px'
BUTTON_PADDING = '10px'

SUCCESS_DIALOG_FONT_SIZE = 12
ERROR_DIALOG_FONT_SIZE = 6

# Colors
BACKGROUND_COLOR = '#2e2e2e'

BUTTON_BACKGROUND_COLOR = '#333'
BUTTON_HOVER_COLOR = '#35393d'
BUTTON_PRESSED_COLOR = '#e78450'

FIELD_BACKGROUND_COLOR = '#333'
FIELD_HOVER_COLOR = '#35393d'
FIELD_FOCUS_COLOR = '#414449'

LABEL_TEXT_COLOR = '#e0e2e4'
FIELD_TEXT_COLOR = '#e0e2e4'

CONTROL_BUTTON_BACKGROUND_COLOR = '#2e2e2e'
CONTROL_BUTTON_HOVER_COLOR = '#35393d'

PROCESS_BUTTON_BACKGROUND_COLOR = '#d77337'
PROCESS_BUTTON_HOVER_COLOR = '#e78450'
PROCESS_BUTTON_PRESSED_COLOR = '#e78450'
