#!/bin/bash

SETUP_SCRIPT="$SNAP/user-data/user-data-copy.sh"

# Example check - adapt according to your specific needs
if [ ! -f "$SNAP_USER_DATA/csv/allTransactions.csv" ]; then
    echo "Setup required. Executing $SETUP_SCRIPT..."
    bash "$SETUP_SCRIPT"
else
    echo "Setup already completed."
fi

python3 $SNAP/usr/lib/transaction-decorator/src/gui.py
